docker stop springtestcase_api_1 springtestcase_approver_1 springtestcase_idgenerator_1 springtestcase_mailer_1
docker rm springtestcase_api_1 springtestcase_approver_1 springtestcase_idgenerator_1 springtestcase_mailer_1
docker rmi springtestcase_api:latest springtestcase_approver:latest springtestcase_idgenerator:latest springtestcase_mailer:latest